// flow-typed signature: 60b5f62bb5a9c1da98ed14e0b90a105f
// flow-typed version: <<STUB>>/koa-advanced-handle-error_v0.1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-advanced-handle-error'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-advanced-handle-error' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-advanced-handle-error/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-advanced-handle-error/dist/index.js' {
  declare module.exports: $Exports<'koa-advanced-handle-error/dist/index'>;
}
declare module 'koa-advanced-handle-error/index' {
  declare module.exports: $Exports<'koa-advanced-handle-error'>;
}
declare module 'koa-advanced-handle-error/index.js' {
  declare module.exports: $Exports<'koa-advanced-handle-error'>;
}
